name: af
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.3.1
  - anyio=4.11.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.5
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.11.13
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fonttools=4.60.0
  - fqdn=1.5.1
  - freetype=2.14.1
  - gast=0.6.0
  - giflib=5.2.2
  - google-pasta=0.2.0
  - grpcio=1.71.0
  - h11=0.16.0
  - h2=4.3.0
  - h5py=3.14.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9e
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - keras=3.11.2
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.0
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20250127.0
  - libaec=1.1.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcurl=8.14.1
  - libdeflate=1.22
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgrpc=1.71.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libpng=1.6.50
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libwebp-base=1.6.0
  - libxcb=1.13
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.9
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minizip=4.0.10
  - mistune=3.1.4
  - mkl=2024.2.2
  - ml_dtypes=0.5.1
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - namex=0.1.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - numpy=2.0.2
  - openjpeg=2.5.0
  - openssl=3.5.3
  - opt_einsum=3.4.0
  - optree=0.17.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.2
  - pandocfilters=1.5.0
  - parso=0.8.5
  - patsy=1.0.1
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=25.2
  - platformdirs=4.4.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - protobuf=5.29.3
  - psutil=7.1.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-flatbuffers=25.2.10
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qhull=2020.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.2
  - qtwebsockets=6.7.3
  - re2=2024.07.02
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.1.0
  - rpds-py=0.27.1
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8
  - sqlite=3.50.4
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - tbb=2021.13.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.1
  - tensorflow-base=2.18.1
  - termcolor=3.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.17.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - filelock==3.19.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - mpmath==1.3.0
      - multidict==6.6.4
      - networkx==3.5
      - neurokit2==0.2.12
      - peakutils==1.3.5
      - propcache==0.3.2
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - pyqtgraph==0.13.7
      - pyserial==3.5
      - pyshimmer==1.0.0
      - pywavelets==1.9.0
      - soundfile==0.13.1
      - sympy==1.14.0
      - torch==2.8.0
      - torchvision==0.23.0
      - wfdb==4.3.0
      - yarl==1.20.1
prefix: C:\Users\achma\miniconda3\envs\af
